### ISSUE TITLE
Address search on iPhone 5, blue artefact

### ISSUE THREAD

**Issue by stevenday** [mysociety/zurich_mobile#13]
From: https://github.com/mysociety/FixMyStreet-Commercial/issues/463

> Tobias writes:
> 
> > If the address search is used on the iOS app on an iPhone5, then the lower half of the screen gets blue (see attached “Foto.png”)
> 
> ![foto](https://f.cloud.github.com/assets/28139/1888085/359a22d8-7a08-11e3-9b24-45db3f4dcda6.png)

**Comment by dracos** [comment]
Too old
