### ISSUE TITLE
Occasional iOS display issues

### ISSUE THREAD

**Issue by stevenday** [mysociety/zurich_mobile#8]
From: https://github.com/mysociety/FixMyStreet-Commercial/issues/365

> > "Sometimes the app displays strangely. It’s hard to recreate those cases, but most of the times it occurred when the keyboard was displayed and the user then clicked back in- to the “app-screen”...
> 
> It seems as if certain parts of the app (like the header or the address search) can be moved around if the keyboard is displayed."
> 
> Not sure how to resolve this

**Comment by dracos** [comment]
Too old
