### ISSUE TITLE
Map controls do not function correctly after a report had been made on Android

### ISSUE THREAD

**Issue by stevenday** [mysociety/zurich_mobile#9]
From: https://github.com/mysociety/FixMyStreet-Commercial/issues/374

> After a report has been made, the map doesn’t behave very well. We noticed that scrolling now only works when the finger swipes from the crosshair outwards. It doesn’t work when swiped from the outside in.
> Also, the buttons for the maptype and GPS don’t work directly after a report has been submitted.
> If the address arch is used and the map cen- ters around a new location, then everything seems to work again.
> 
> 4.2 and 4.0.4

**Comment by dracos** [comment]
Too old
